* TODO Professional Checklist
** Bio BLURB
This is your bio blurb (80-120 words), which will be published on the public roster and shared with potential employers. Please make sure you check grammar and punctuation.
** Portfolio
Simple, well-designed, and responsive site.
example : https://shawncharles.com
*** About Me
It could be about your bio blurb
*** Contact info
*** Coding Project
- class assignment
- passion project
- paid work
*** Is it live / on the internet?
*** Check stylesheets
*** Ssl security warning?
** Resume
It must be geared towards software engineering (web development), and should have the following:
- Template: https://bit.ly/3d908uc
- Resources (only use free version): https://canva.com | https://resume.io
*** Summary
*** Skills
*** Work Experience
- Starting with most recent to the last 5 years
- Write everything in past tense
- Older or irrelevant experiences only include a small description
- Bullet points
  Every Bullet point has an outcome, not just a listed task
*** Volunteering  (Optional)
*** Education
*** Contact Information
*** Resume is one-page only
*** Important
For some jobs, you may need to tailor your resume to be more specific to the position. Cover letters also require the same level of attention and personalization. Before submitting an application, make sure to pull keywords directly from the job description and implement them into your resume and cover letter.
** LINKEDIN/ANGELLIST
LinkedIn and AngelList is your professional resume. You should have the following:
example : https://www.linkedin.com/in/shawnxcharles/
*** Professional Headshot
*** Set up your title with your current role: Software Engineer at 100Devs
*** Location is listed as City, Location
*** Update Contact Info (Email + Link to Twitter, Portfolio, Github)
*** Make sure to personalize your LinkedIn URL (You can edit from the  top right corner)
*** Add an About section, and include your Story Bio Blurb here
*** List your experience, starting with your most recent work, make sure to include bullet points
*** Volunteer Experience (Optional)
*** Education
*** LinkedIn Skills & Endorsements (add your tech skills and order them)
*** Languages
*** TODO Join #100Devs Group on linked in https://www.linkedin.com/groups/9037281/
** GITHUB
Github is an opportunity to show tech recruiters and engineering managers your code. It should have the following:
- example: https://github.com/CharlesCreativeContent
- resources: https://rahuldkjain.github.io/gh-profile-readme-generator/ https://github.com/alecortega/portfolio-template
*** Professional Headshot
*** Title Software Engineer at @100Devs + short description.
*** Location, City / Country
*** Link to your portfolio
*** Every project has a readme w/ a solid picture and hosted somewhere
** TWITTER
Twitter is a great way for you to stay in touch with news, learn from other developers, build your brand presence, and most importantly grow your network. You should have the following:
example: https://twitter.com/IbrahimCodes
*** Professional Headshot
*** Title Software Engineer at 100Devs + short description.
*** Location, yours
*** Link to your portfolio
*** Following 50 engineers where you will be applying
*** Send one tweet out
** COVER LETTER/COVER EMAIL
Some companies still request cover letters as part of their application process. It’s always a great way to show how interested you are in a company/opportunity. While it’s great to talk about your former background and experience, we want to focus on your new software engineering skills. There are typically four parts in a cover letter:
Example:
https://docs.google.com/document/d/1UERcWv8rIPROZXEZG5ZFBE6_z8Yhl90ZhAla_owahP0/edit?usp=sharing
*** INTRODUCTION (1 short opening paragraph)
- How did you find the job?
- Do you know anyone at the company?
- What’s the role you are applying to?
- What’s the company?
- Is there a specific engineering team?
- List some of the qualities that would make you a fit for the role

* Class 15
* Class 16
