* Ringkasan Tata Cara Shalat
:PROPERTIES:
:author:   [[http://penerbitzamzam.com/penulis/dr-ahmad-bin-muhammad-al-khalil/][Prof. Dr. Ahmad bin Muhammad Al-Khalil]]
:year:     2019
:END:

** TODO Perbaiki external links
** Tata Cara Shalat

"Jika kamu hendak mengerjakan shalat, maka sempurnakanlah wudhu, lalu menghadap ke arah Kiblat, setelah itu bertakbirlah, kemudian bacalah ayat-ayat A;-Quran yang mudah bagimu. Kemudian rukuklah hingga kamu rukuk dengan tenang, dan bangkitlah dari rukuk hingga kamu berdiri tegak. Lalu sujudlah hingga kamu sujud dengan tenang, dan bangkitlah hingga kamu duduk dengan tenang, lalu bangkitlah hingga kamu duduk dengan tenang, dan kerjakanlah semua hal tersebut pada seluruh shalatmu." [[* HR. Bukhari (6251)][HR. Bukhari (6521)]] dan [[* HR. Muslim (397)][HR. Muslim (397)]]

** Persiapan untuk Shalat
*** Wudhu

- wajib berwudhu. [[* QS. Al-Ma'idah:6][QS. Al-Ma'idah:6]]
- disunnahkan untuk memperbaharui wudhu sebelum shalat. [[* HR. Bukhari (214)][HR. Bukhari (214)]]

*** Adab Masjid

- melaksanakan shalat Tahiyat Masjid sebelum duduk. [[*][Muttafaq 'Alaih [3] Majmu' Al-Fatawa: (22/494)]]
- duduk menunggu waktu iqamah dikumandangkan sambil berzikir dan membaca Al-Quran. [[* HR. Bukhari (659)][HR. Bukhari (659)]]
- imam wajib meluruskan saf-saf

** Shalat
*** Niat Shalat

merupakan syarat shalat wajib.

*** Takbiratulihram

merupakan rukun shalat
- disunnahkan untuk bertakbir bersamaan dengan mengangkat kedua tangan
- posisi jari jemari diluruskan dan dirapatkan, karena lebih dekat kepada khusyuk daripada direnggangkan atau dikepalkan
- posisi kedua tangan sejajar dengan kedua pundak atau kedua telinga
- bagi wanita sebagian ulama mengatakan bahwa mengangkat kedua tangan lebih rendah dan tidak perlu tinggi seperti laki-laki
- wajib bagi imam mengeraskan suara saat bertakbir

*** TODO Qiyaam (Berdiri) [cari sumber dalil]

merupakan rukun shalat
- jika tidak mampu berdiri (sakit dll) sehingga menghilangkan kekhusyukan maka boleh duduk/tidur [[file:./Getting Started with Orgzly.org::*Search][QS. At-Tagaabun:16]] [[*][HR. Bukhari (7288)]] [[*][HR. Muslim (1337)]]
- syarat berdiri bagi yang mampu hanya ada di dalam shalat wajib
- melipatkan kedua tangan saat berdiri, dengan meletakkan tangan kanannya di atas lengan tangan kiri. posisi tangannya bebas diletakkan di atas pusar/diantara dada dan perut karena tidak ada dalil sahih mengenai hal tersebut [[*][HR. Bukhari (740)]] [[*][HR. Muslim (401)]]

*** Pandangan Mata

melihat ke tempat sujud, jika mengangkat pandangannya maka ia telah menyelisihi sunnah

*** TODO Doa Iftitah [Sertakan doa dan dalil]

ada beberapa macam doa iftitah dan semuanya diperbolehkan. sunnah membaca dengan pelan/tidak mengeraskan suara.

*** Doa istiazah

sunnah membaca doa istiazah sebelum membaca Al-Faatihah dengan pelan. [[*][QS. An-Nahl:98]]
- A'uzu billaahi minasy-syaitaanir-rajiim

*** Basmalah

disyariatkan bagi orang shalat setelah membaca istiazah dan sebelum membaca Al-Faatihah. [[*][HR. Nasai (905)]]

*** Membaca Surah Al-Faatihah

rukun shalat. [[*][HR. Bukhari (756)]] [[*][HR. Muslim (394)]] [[*][HR. Muslim (395)]]
- wajib belajar membaca
- jika tidak bisa juga maka harus membaca dzikir
- disyariatkan bagi imam untuk mengeraskan suaranya pada saat shalat Isya, Magrib dan Subuh (Shalat Jahriyyah) dan mengecilkan suara pada saat shalat dzuhur dan asar (Shalat Sirriyyah)
- harus melafalkan -yaitu menggerakkan lidahnya- bacaan dan dzikir yang sifatnya wajib. [[*][Mukhtasar Al-Fataawaa Al-Misriyyah (43)]]
- makmum tidak perlu membaca ayat pada Shalat Jahriyyah, apabila ia mendengar bacaaan imam, seperti bacaan Surah Al-Faatihah maupun bacaan surah-surah yang lain. [[*][Majmuu Al-Fataawaa]]

*** Mengucapkan "Aamiin" setelah Al-Faatihah

merupakan sunnah
- [[*][Munfarid]] (orang yang shalat sendirian) mengucapkan "Aamiin" setelah dirinya membaca Al-Faatihah
- Imam mengucapkan "Aamiin" membaca Al-Faatihah
- Imam dan makmum mengeraskan bacaan "Aamiin" dan disyariatkan bagi makmum mengucapkan "Aamiin" bersamaan dengan imam [[*][HR. Bukhari (780)]] [[*][HR. Muslim (410)]]

*** TODO Bacaan setelah Al-Faatihah [cari sumber dalil]

- disunnahkan untuk membaca sebuah surah pada dua rakaat yang pertama saja 
- bacaannya dikeraskan pada shalat yang dikeraskan Al-Faatihah dan dipelankan pada shalat yang dipelankan Al-Faatihah
- memperlama bacaan pada rakaat pertama
- disunnahkan bagi imam di waktu subuh pada hari jumat membaca surah As-Sajadah dan Al-Insaan [[*][Badaa'i Al-Fawaa'id (4/63)]]

*** Memperlama bacaan shalat

- disunnahkan membaca satu surah dengan sempurna atau boleh membaca sebagian surah dari awalnya saja [[*][HR. Nasai (991)]] [[*][HR. Bukhari (765)]] [[*][HR. Muslim (463)]]
- dibolehkan membaca ayat-ayat terakhir dari surah tertentu, akan tetapi dimakruhkan terus-menerus melakukannya
- membaca dalam shalat Magrib dengan Qisaar Al-Mufassal (surah-surah pendek dari surah Ad-Duhaa sampai An-Naas)
- membaca dalam shalat Subuh dengan Tiwaal Al-Mufassal (surah-surah panjang dari Qaaf sampai An-Naba)
- sementara shalat Isya, Zuhur dan Asar dengan Awsaat Al-Mufassal (surah-surah yang pertengahan dari surah An-Naba hingga Ad-Duhaa) [[*][HR. Nasai (982)]] [[*][HR. Ibnu Majah (827)]] [[*][HR. Ahmad (7991)]] [[*][HR. Tirmizi (307)]]

* Tafseer As-Sa'di Vol 1 Juz 1
:PROPERTIES:
:CREATED:  [2024-09-06 Fri 22:39]
:END:

* TODO Ringkasan Buku "Himpunan Fatwa Syaikh Abdul Aziz Bin Baz Rahimahullah Dalam Permasalahan Udzur Kejahilan" (Fix semua istilah dalam Islam)
:PROPERTIES:
:CREATED:         [2024-10-28 Mon 12:09]
:AUTHOR:          Syaikh Ali Bin Saud Al-Arjani AL-Ajami
:TRANSLATIONS_BY: Jabir Abu Unaisah
:END:

** TODO Bismillahhirrahmanirrahim (ketik dalam Bahasa Arab)

** Kata Pengantar : Syaikh Shalih Bin Fauzan Al Fauzan

Segala puji hanyalah milik Allah Subhanahuwataala. Sesungguhnya persoalan udzur kejahilan adalah persoalan yang didalamnya ada perincian, berbeda dengan pendapat murji'ah yang hanya bersandar kepada udzur kejahilan ini tanpa tidak perlu merincinya. Hal ini karena orang yang jahil ada dua keadaan :
- Keadaan pertama, ia berada dilokasi yang jauh dan terisolir, dakwah Islam belum sampai kepadanya. maka ia diberi udzur kejahilan hingga dakwah Islam sampai kepadanya jika memang ia menginginkan untuk memahaminya.
- Keadaan kedua, dakwah Islam telah sampai kepadanya. maka ia tidak diberi udzur kejahilan karena ia sendiri yang malas untuk mencari pengetahuan dan malas untuk menghilangkan kejahilan dari dirinya.
dua keadaan itu dalam persoalan-persoalan keyakinan yang jelas.
adapun dalam persoalan-persoalan cabang yang samar, terbuka ruang ijtihad didalamnya, maka diberikan udzur kejahilan hingga dijelaskan kepadanya.
Adapun dimasa ini, walhamdulillah, didapati berbagai peralatan komunikasi dan peralatan informasi sehingga tidak lagi ada udzur bagi seorang pun untuk bertahan dalam kejahilannya. Allah Subhanahuwataala berfirman: 

وَمَآ أَرْسَلْنَا مِن قَبْلِكَ إِلَّا رِجَالًۭا نُّوحِىٓ إِلَيْهِمْ ۚ فَسْـَٔلُوٓا۟ أَهْلَ ٱلذِّكْرِ إِن كُنتُمْ لَا تَعْلَمُونَ ٤٣

"Dan Kami tidak mengutus sebelum engkau (Muhammad), melainkan orang laki-laki yang Kami beri wahyu kepada mereka; maka bertanyalah kepada orang yang mempunyai pengetahuan jika kamu tidak mengetahui,"
We did not send ˹messengers˺ before you ˹O Prophet˺ except mere men inspired by Us. If you ˹polytheists˺ do not know ˹this already˺, then ask those who have knowledge ˹of the Scriptures˺.
(QS. An-Nahl 16: Ayat 43)

Tidak lagi tersisa udzur bagi seorang pun untuk bertahan dalam kejahilannya karena dia sendirilah yang malas.
Kutipan-kutipan yang dibawakan oleh saudara kami Asy Syaikh Ali bin Saud Al Ajami didalamnya termuat penjelasan yang gamblang akan hal tersebut, semoga Allah membalas beliau dengan limpahan kebaikan serta semoga apa yang beliau tulis ini bermanfaat.

** TODO BAB I HIMPUNAN FATWA ASY SYAIKH ABDUL AZIS BIN BAZ RAHIMAHULLAH

*** Kewajiban bagi Umat Islam dalam Perkara Udzur Kejahilan

Kewajiban setiap mukmin adalah menuntut ilmu dan mendalami urusan agamanya serta bertanya kepada ulama. (TODO: QS. An-Nahl :43) dan tidak boleh berfatwa tanpa ilmu (TODO: HR. Abu Dawud 336) (TODO: HR. Bukhari 71) Maka kewajiban umat islam baik lelaki maupun wanita adalah mempelajari agamanya dan mendalaminya serta bertanya akan perkara yang tidak mereka ketahui, tidak berdiam dalam kejahilan, dan tidak berpaling, tidak pula tidak peduli. Mereka diciptakan untuk beribadah kepada Allah dan mentaatinya, sementara tidak ada cara untuk beribadah dan taat kecuali dengan ilmu, tidak bisa hal itu terwujud secara spontan tanpa mencari tahu dan tanpa bertanya, akan tetapi wajib untuk mempelajari ilmu, wajib untuk bertanya kepada ulama sehingga orang yang bodoh akan mengetahui.
dan setiap orang berkewajiban untuk menuntut ilmu serta bertanya, jangan rela menjadi pengekor orang lain, tetapi hendaknya ia bertanya. Allah berfirman (TODO: QS. An-Nahl :43), artinya tidak diperkenankan bagi seseorang untuk bertahan diatas kekafiran dan kesyirikan hanya karena ia melihat bahwa orang-orang melakukannya, tanpa ia bertanya atau mencari tahu.
Maka, kewajiban bagi setiap orang yang sudah baligh dan berakal waras ialah bertanya serta berupaya mencocoki kebenaran, untuk mendalami agamanya. Janganlah ia rela untuk sama dengan kaum awam, mengekor kekafiran dan kesesatan serta amalan-amalan rusak mereka. Akan tetapi ia wajib bertanya kepada ulama, perhatian kepada ulama, bertanya tentang ketidak tahuannya, baik perkara tauhid ataupun perkara lainnya.(TODO: QS. An-Nahl :43)

*** Kewajiban bagi Ulama dalam Perkara Udzur Kejahilan

Kewajiban ulama Islam adalah mengingatkan masyarakat, memperingatkan mereka dari kesyirikan ini, membimbing dan menasehati mereka di masjid-masjid ataupun ditempat lainnya.

*** Penjelasan tentang siapa Ahlul Fatrah

Ahlul Fatrah adalah orang-orang yang risalah Nabi Muhammad Saw belum sampai kepada mereka. Mereka tidak mendengar Al-Quran, tidak pula mendengar Rasulullah Saw, mereka ini disebut ahlul fatrah. Adapun orang yang Al-Quran telah sampai kepada mereka atau berita kerasulan Muhammad Saw telah sampai kepada mereka, bahwa Allah telah mengutus beliau kepada seluruh manusia, mendakwahi mereka, namun kemudiaan orang tersebut tidak memperdulikannya, maka bukan ahlul fatrah. Tentang nasib ahlul fatrah, pendapat yang benar bahwa dihari kiamat nanti Allah akan menguji mereka, barangsiapa diantara mereka yang menyambut ujian tersebut maka akan masuk surga, dan barangsiapa yang durhaka maka akan masuk neraka. Semoga Allah menyelamatkan kita.

*** Persoalan Udzur Kejahilan dalam Perkara Aqidah

Aqidah merupakan perkara paling penting dan kewajiban terbesar. Hakikat Aqidah adalah beriman kepada Allah, kepada para malaikat, kitab-kitabnya, rasul-rasulnya, hari akhir dan kepada takdir yang baik maupun yang buruk. Beriman bahwa Allah adalah satu-satunya yang berhak di ibadahi, dan mempersaksikan akan hal tersebut, yaitu mempersaksikan bahwa tidak ada yang berhak diibadahi kecuali Allah. Seorang mukmin mempersaksikan bahwa tidak ada yang berhak diibadahi kecuali Dia yang Maha Suci dan Maha Tinggi. Juga mempersaksikan bahwa Muhammad adalah Rasul utusan Allah, Allah mengutus beliau kepada seluruh jin dan manusia, beliau adalah penutup seluruh para nabi. Semua ini harus dia imani, ini merupakan inti aqidah, sehingganya harus dimiliki oleh setiap orang baik lelaki maupun wanita. Ini merupakan azas Islam, azas agama. Sebagaimana juga wajib beriman terhadap segala yang diberitakan oleh Allah dan Rasulnya dari berita-berita tentang kiamat, tentang surga dan neraka, tentang pengadilan dan pembalasan, tentang pembagian buku catatan amal, dimana ada yang menerimanya dengan tangan kanan serta ada yang menerimanya dengan tangan kiri, tentang penimbangan amal dan lain sebagainya dari berita-berita yang telah dibawa oleh Al-Quran dan Hadits-Hadits Nabi Muhammad.
Kejahilan dalam perkara ini bukanlah udzur, setiap mukmin wajib mengetahui ini dan mencari tahu tentangnya, tidak diberi udzur baginya jika kemudian ia berkata diriku bodoh tentang perkara-perkara ini, sementara ia hidup ditengah kaum muslimin, Al-Quran dan Sunnah Rasulullah telah sampai kepadanya, orang seperti ini disebut pembangkang, disebut juga orang tidak peduli dan acuh terhadap perkara yang penting seperti ini, ia tidak diberi udzur. Adapun orang yang hidup dilokasi yang jauh dari umat Islam, diujung dunia yang tidak berpenghunikan orang islam sama sekali, Al-Quran dan Sunnah belum sampai kepadanya, maka orang seperti ini diberi udzur dan statusnya adalah ahlul fatrah jika ia sampai mati dalam keadaannya tersebut.
Perkara udzur kejahilan ini (aqidah) bukanlah perkara ijtihadiyah yang berubah-ubah tergantung waktu dan tempat. Kecuali jika ia hidup ditempat yang dakwah belum menjangkaunya, Al-Quran dan Sunnah belum menjangkaunya.

*** Hukum Udzur Kejahilan dalam Perkara Tauhid

Barangsiapa yang hidup di negeri tauhid, tidak diberi udzur kejahilan atas perbuatan mereka tersebut. Selama mereka hidup ditengah umat Islam, bukan dimasa fatrah, bukan pula hidup dilokasi yang jauh dari orang Islam, maka tidak ada udzur kejahilan bagi mereka dalam perkara tauhid. Kapan ia melakukan kesyirikan maka divonis Musyrik. Sebagaimana hal ini sekarang terjadi di Mesir, Syam dan selain keduanya, di beberapa negara, dikuburan Al Badawi ataupun kuburan selainnya.
Dan tidak ada udzur kejahilan baik dalam perkara tauhid rububiyah, uluhiyah atau nama dan sifat Allah. Setiap orang beriman wajib untuk mentauhidkan Allah, untuk mengimani bahwa Allah adalah Rabbal Alamin, bahwa Allah adalah maha pencipta lagi maha mengetahui, dan bahwa Allah satu-satunya Rabb, tidak ada pencipta selain Dia, bahwa Allah adalah satu-satunya yang berhak diibadahi, selain Dia tidak berhak sedikitpun, bahwa Dia maha memiliki nama-nama yang dipuncak keindahan serta memiliki sifat-sifat yang maha tinggi, bahwa tidak ada sesuatupun yang sama dengan Dia atau sepadan dengan Dia.
Orang yang tidak beriman akan hal ini maka tidak ada udzur baginya. Kecuali jika ia hidup terisolir dari umat islam, di dataran yang wahyu Allah belum sampai kepadanya, maka dalam keadaan ini ia diberi udzur dan statusnya adalah sebagai ahlul fatrah, dihari kiamat nanti ia akan diuji, jika ia lulus ujian maka akan masuk surga, namun jika tidak lulus ujian maka akan masuk neraka.Adapun seseorang hidup ditengah umat islam, mendengar Al-Quran dan Sunnah kemudian ia bertahan diatas kesyirikan, bertahan diatas pengingkaran terhadap sifat-sifat Allah maka ia tidak diberi udzur. Kita memohon keselamatan kepada Allah.
Telah Shahih dari Nabi Muhammad bahwa beliau bersabda kepada seorang yang bertanya tentang ayahnya : (HR. Muslim No. 203 Kitab Iman Bab Penjelasan barangsiapa yang Mati Diatas Kekafiran)
Ayah beliau wafat pada masa jahiliyah, karena mereka kala itu statusnya berada dalam syariat yang mereka terima dari Nabi Ibrahim, yaitu tauhid. Sedangkan ibu beliau juga wafat dalam kejahiliyahan, (TODO: Cari Hadisnya) Beliau meminta ijin kepada Allah untuk mendo'akan ampunan bagi sang ibu namun Allah tidak mengizinkan. Kemudian beliau meminta izin kepada Allah untuk mengunjungi makam sang ibu maka Allah mengizinkannya. (TODO: Cari Ayat yang menjelaskan bahwa tidak boleh meminta ampunan bagi orang kafir) Ini semua menunjukkan bahwa siapapun yang mati kafir maka tidak boleh dimintakan ampunan kepada Allah atau didoakan kepada Allah, meskipun matinya dimasa kejahiliyahan. Maka terlebih lagi jika ia hidup ditengah kaum muslimin, diantara ahli tauhid, diantara orang-orang yang membaca Al-Quran serta mendengar Hadits-Hadits Rasulullah, tentu orang ini lebih pantas untuk dinyatakan sebagai kafir serta hukum yang diterapkan kepada orang-orang kafir juga diterapkan kepadanya. Realitanya, banyak dari mereka apabila mendengar orang yang mendakwahkan tauhid dan memperingatkannya dari kesyirikan maka akan menolak, sombong dan menentang atau bahkan memilih berperang demi agamanya yang batil, demi taklidnya kepada para leluhurnya. (Todo: )La haula wala quwwata illa billah

*** Persoalan Udzur Kejahilan dalam Perkara Fiqh, Dll

Adapun persoalan-persoalan yang terkadang hukumnya samar bagi sebagian orang seperti sebagian hukum shalat atau sebagian hukum zakat atau sebagian hukum haji, atau dalam cabang pembahasan sifat Allah, disebagian sifat Allah yang terkadang tidak diketahui, dalam perkara ini terkadang seseorang diberi udzur kejahilan atasnya, karena tidak semua orang mampu mendalami persoalan-persoalan seperti ini, jadi perkaranya lebih ringan. 
