* SKB Wawancara
** Kelebihan dan Kekurangan

   Kelebihan : saya bekerja keras, jujur, suka belajar hal yang baru, bisa berbahasa inggris, mampu mengoperasikan banyak alat perkantoran, pandai menggunakan komputer
   Kekurangan : saya harus fokus saat bekerja

** Latar belakang pendidikan, pengalaman berorganisasi, dan pengalaman bekerja

   untuk mengetahui kompetensi sosial yang anda miliki: 

*** sekolah di SMAN 1 Banda Aceh
*** di rohis SMA, anggota pengurus ekskul bulutangkis SMA
*** bekerja di Fotokopi
*** mengikuti Course/pelatihan di bidang pemrograman web
** Profil Kemenkumham RI

   https://www.kemenkumham.go.id/profil/tentang-kementerian-hukum-ri/sejarah-kementerian-hukum-ri

*** Sejarah

Kementerian Hukum dan Hak Asasi Manusia Republik Indonesia (disingkat Kemenkumham RI) adalah kementerian dalam Pemerintah Indonesia yang membidangi urusan hukum dan hak asasi manusia. Kementerian Hukum dan Hak Asasi Manusia berada di bawah dan bertanggung jawab kepada Presiden. Kementerian Hukum dan Hak Asasi Manusia dipimpin oleh seorang Menteri yang sejak 27 Oktober 2014 dijabat oleh Yasonna Laoly. Kemenkumham beberapa kali mengalami pergantian nama yakni: "Departemen Kehakiman" (1945-1999), "Departemen Hukum dan Perundang-undangan" (1999-2001), "Departemen Kehakiman dan Hak Asasi Manusia" (2001-2004), "Departemen Hukum dan Hak Asasi Manusia" (2004-2009), dan "Kementerian Hukum dan Hak Asasi Manusia" (2009-sekarang).
Kementerian Hukum dan Hak Asasi Manusia pertama kali dibentuk pada tanggal 19 Agustus 1945 dengan nama Departemen Kehakiman. Menteri Kehakiman yang pertama menjabat adalah Soepomo. Kementerian Hukum dan Hak Asasi Manusia pada zaman pemerintahan Belanda disebut Departemen Van Justitie yaitu berdasarkan peraturan Herdeland Yudie Staatblad No.576.
Dalam sidang PPKI tahun 1945 menetapkan mengenai Departemen Kehakiman dalam struktur Negara menurut UUD. Dalam UUD tadi disebutkan departemen termasuk Departemen Kehakiman yang mengurus tentang pengadilan, penjara, kejaksaan dan sebagainya. Dalam sidang PPKI tersebut dibuat pula penetapan tentang tugas pokok masalah ruang lingkup tugas Departemen Kehakiman walaupun secara singkat masih mengacu kepada peraturan Herdeland Yudie Staatblad No.576.
Pada tanggal 1 Oktober 1945 kewenangan Departemen Kehakiman diperluas yakni Kejaksaan berdasarkan Maklumat Pemerintah tahun 1945 tanggal 1 0ktober 1945 dan Jawatan Topograpi berdasarkan Penetapan pemerintah tahun 1945 Nomor 1/S.D. Jawatan Topograpi kemudian dikeluarkan dari Departemen Kehakiman dan masuk ke Departemen Pertahanan berdasarkan Penetapan Pemerintah tahun 1946 nomor 8/S.D.
Ketika Departemen Agama dibentuk pada tanggal 3 Januari 1946, Mahkamah Islam Tinggi dikeluarkan dari Departemen Kehakiman Republik Indonesia dan masuk ke Departemen Agama Republik Indonesia berdasarkan penetapan pemerintah tahun 1946 Nomor 5/S.D.
Pada 22 Juli 1960, rapat kabinet memutuskan bahwa kejaksaan menjadi departemen dan keputusan tersebut dituangkan dalam Keputusan Presiden RI Nomor 204/1960 tertanggal 1 Agustus 1960 yang berlaku sejak 22 Juli 1960. Sejak itu pula, Kejaksaan RI dipisahkan dari Departemen Kehakiman. Pemisahan tersebut dilatarbelakangi rencana kejaksaan mengusut kasus yang melibatkan Menteri Kehakiman pada saat itu.
Pengalihan Peradilan Umum dan Peradilan Tata Usaha Negara dari Kementerian Hukum dan Hak Asasi Manusia ke Mahkamah Agung berawal dari Undang-Undang No 35 Tahun 1999 tentang Ketentuan-ketentuan Pokok Kekuasaan Kehakiman yang kemudian dijabarkan dalam Undang-Undang No. 4 Tahun 2004 tentang Kekuasaan Kehakiman dan Undang-Undang No. 5 Tahun 2004 tentang Perubahan atas Undang-Undang No. 14 Tahun 1985 tentang Mahkamah Agung. Pada tanggal 23 Maret 2004 Presiden Megawati mengeluarkan Keputusan Presiden RI No. 21 Tahun 2004 tentang pengalihan organisasi, administrasi dan finansial dan lingkungan Peradilan Umum dan Tata Usaha Negara, Pengadilan Agama ke Mahkamah Agung yang kemudian ditindaklanjuti dengan serah terima Pengalihan organisasi, administrasi dan finansial di lingkungan Peradilan Umum dan Peradilan Tata Usaha Negara ke Mahkamah Agung pada tanggal 31 Maret 2004.
Nama Departemen Kehakiman telah beberapa kali berubah nama karena disesuaikan dengan fungsi dari Departemen tersebut yaitu dari Departemen Kehakiman menjadi Departemen Hukum dan Perundang Undangan dan sekarang menjadi Kementerian Hukum Dan Hak Asasi Manusia.
Kantor wilayah (kanwil) Kementerian Hukum dan Hak Asasi Manusia merupakan instansi vertikal Kementerian Hukum dan Hak Asasi Manusia yang berkedudukan di setiap provinsi, yang berada di bawah dan bertanggung jawab kepada Menteri Hukum dan Hak Asasi Manusia. Kanwil terdiri atas beberapa divisi serta sejumlah Unit Pelaksana Teknis (UPT), termasuk Kantor Imigrasi, Lembaga Pemasyarakatan (Lapas), Lapas Terbuka • Lapas Narkotika, Rumah Tahanan Negara (Rutan), Cabang Rutan, Rumah Penyimpanan Benda Sitaan Negara (Rupbasan), Balai Pemasyarakatan (Bapas), Balai Harta Peninggalan (BHP), serta Rumah Detensi Imigrasi (Rudenim).

*** Visi, Misi dan Tata Nilai

Visi :"Kementerian Hukum dan Hak Asasi Manusia yang Andal, Profesional, Inovatif, dan Berintegritas dalam pelayanan kepada Presiden dan Wakil Presiden untuk mewujudkan Visi dan Misi Presiden dan Wakil Presiden Indonesia Maju yang Berdaulat, Mandiri, dan Berkepribadian berlandaskan Gotong Royong".
Misi :
    Membentuk peraturan Perundang-Undangan yang berkualitas dan melindungi kepentingan nasional;
    Menyelenggarakan pelayanan publik di bidang hukum yang berkualitas;
    Mendukung penegakan Hukum di Bidang Kekayaan Intelektual, Keimigrasian, Administrasi Hukum Umum, dan Pemasyarakatan yang bebas dari korupsi, bermartabat dan terpercaya;
    Melaksanakan penghormatan, perlindungan dan pemenuhan Hak Asasi Manusia yang berkelanjutan;
    Melaksanakan peningkatan Kesadaran Hukum Masyarakat;
    Ikut serta menjaga stabilitas keamanan melalui peran Keimigrasian dan Pemasyarakatan; serta
    Melaksanakan tata laksana pemerintahan yang baik melalui Reformasi Birokrasi dan Kelembagaan.
Tata Nilai:
 1. Profesional  	: 	Aparatur Kementerian Hukum dan HAM adalah aparat yang bekerja keras untuk mencapai tujuan organisasi melalui penguasaan bidang tugasnya, menjunjung tinggi etika dan integirtas profesi;
 2. Akuntabel 	: 	Setiap kegiatan dalam rangka penyelenggaraan pemerintah dapat dipertanggungjawabkan kepada masyarakat sesuai dengan ketentuan atau peraturan yang berlaku;
 3. 	Sinergi 	: 	Komitmen untuk membangun dan memastikan hubungan kerjasama yang produktif serta kemitraan yang harmonis dengan para pemangku kepentingan untuk menemukan dan melaksanakan solusi terbaik, bermanfaat, dan berkualitas;
 4. 	Transparan 	: 	Kementerian Hukum dan HAM menjamin akses atau kebebasan bagi setiap orang untuk memperoleh informasi tentang penyelenggaraan pemerintahan, yakni informasi tentang kebijakan, proses pembuatan dan pelaksanaannya, serta hasil-hasil yang dicapai;
 5. 	Inovatif 	: 	Kementerian Hukum dan HAM mendukung kreatifitas dan mengembangkan inisiatif untuk selalu melakukan pembaharuan dalam penyelenggaraan tugas dan fungsinya.

*** Tugas dan Fungsi

Tugas :
"Kementerian Hukum dan Hak Asasi Manusia mempunyai tugas menyelenggarakan urusan pemerintahan di bidang hukum dan hak asasi manusia untuk membantu Presiden dalam menyelenggarakan pemerintahan negara."
Fungsi:
Dalam melaksanakan tugas sebagaimana dimaksud dalam Pasal 4 Peraturan Menteri Hukum dan HAM Nomor 28 Tahun 2023, Kementerian Hukum dan Hak Asasi Manusia menyelenggarakan fungsi:

    perumusan, penetapan dan pelaksanaan kebijakan di bidang peraturan perundang-undangan, administrasi hukum umum, pemasyarakatan, keimigrasian, kekayaan intelektual, dan hak asasi manusia;
    koordinasi pelaksanaan tugas, pembinaan, dan pemberian dukungan administrasi kepada seluruh unsur organisasi di lingkungan Kementerian Hukum dan Hak Asasi Manusia;
    pengelolaan barang milik/kekayaan negara yang menjadi tanggung jawab Kementerian Hukum dan Hak Asasi Manusia;
    pengawasan atas pelaksanaan tugas di lingkungan Kementerian Hukum dan Hak Asasi Manusia;
    pelaksanaan bimbingan teknis dan supervisi atas pelaksanaan urusan Kementerian Hukum dan Hak Asasi Manusia di daerah;
    pelaksanaan pembinaan hukum nasional;
    perumusan, penyusunan, dan pemberian rekomendasi strategi kebijakan di bidang hukum dan hak asasi manusia;
    pelaksanaan pengembangan sumber daya manusia di bidang hukum dan hak asasi manusia;
    pelaksanaan kegiatan teknis yang berskala nasional;
    pelaksanaan tugas pokok sampai ke daerah; 
    pelaksanaan dukungan yang bersifat substantif kepada seluruh unsur organisasi di lingkungan Kementerian Hukum dan Hak Asasi Manusia; dan
    pelaksanaan fungsi lain yang diberikan oleh Presiden.

*** Struktur Organisasi
** Kode etik profesi

   Sasanti imigrasi: "Bhumi Pura Wira Wibawa" artinya pengawal pintu gerbang yang dalam pelaksanaan tugas berdasarkan asas kemanusiaan, keadilan sehingga menumbuhkan integritas wibawa kepada masyarakat luas
   Tri fungsi imigrasi :
1. Pengaturan tentang berbagai hal mengenai lalu lintas orang keluar, masuk dan tinggal dari dan ke dalam wilayah negara Republik Indonesia;
2. Pengaturan tentang berbagai hal mengenai pengawasan orang asing di wilayah Repubik Indonesia;
3. Pemeriksaan dokumen perjalanan, baik negara yang ditinggalkan, negara yang dikunjungi, maupun negara yang dilalui.
   Panca Bhakti Insan Imigrasi :
1. Takwa
2. Menjunjung tinggi kehormatan
3. Cendekia
4. Integritas Pribadi
5. Inovatif

** Alasan mendaftar CPNS

   berikan jawaban yang memiliki kesan positif: ingin ikut berkontribusi memajukan bangsa dan negara

** Alasan mengapa memilih Ditjen imigrasi
** Tugas dan Fungsi Ditjen Imigrasi

Bagian Kesatu
Kedudukan, Tugas dan Fungsi

Pasal 547

    Direktorat Jenderal Imigrasi berada di bawah dan bertanggung jawab kepada Menteri.
    Direktorat Jenderal Imigrasi dipimpin oleh Direktur Jenderal.

Pasal 548
Direktorat Jenderal Imigrasi mempunyai tugas menyelenggarakan perumusan dan pelaksanaan kebijakan di bidang keimigrasian sesuai dengan ketentuan peraturan perundang-undangan.

Pasal 549
Dalam melaksanakan tugas sebagaimana dimaksud dalam Pasal 548, Direktorat Jenderal Imigrasi menyelenggarakan fungsi:

    perumusan kebijakan di bidang penegakan hukum dan keamanan keimigrasian, pelayanan dan fasilitas keimigrasian, perlintasan negara dan kerja sama luar negeri keimigrasian, dan Teknologi informasi keimigrasian;
    pelaksanaan kebijakan di bidang penegakan hukum dan keamanan keimigrasian, pelayanan dan fasilitas keimigrasian, perlintasan negara dan kerja sama luar negeri keimigrasian, dan teknologi informasi keimigrasian;
    pemberian bimbingan teknis dan supervisi di bidang penegakan hukum dan keamanan keimigrasian, pelayanan dan fasilitas keimigrasian, perlintasan negara dan kerja sama luar negeri keimigrasian, dan teknologi informasi keimigrasian;
    pelaksanaan pemantauan, evaluasi, dan pelaporan di bidang penegakan hukum dan keamanan keimigrasian, pelayanan dan fasilitas keimigrasian, perlintasan negara dan kerja sama luar negeri keimigrasian, dan teknologi informasi keimigrasian;
    pelaksanaan administrasi Direktorat Jenderal Imigrasi; dan
    pelaksanaan fungsi lain yang diberikan oleh Menteri.

** Hukum Menjaga Jenggot

“Potong pendeklah kumis dan biarkanlah (peliharalah) jenggot.” (HR. Muslim no. 623)
“Selisilah orang-orang musyrik. Potong pendeklah kumis dan biarkanlah jenggot.” (HR. Muslim no. 625)
“Pendekkanlah kumis dan biarkanlah (perihalah) jenggot dan selisilah Majusi.” (HR. Muslim no. 626)
“Ada sepuluh macam fitroh, yaitu memendekkan kumis, memelihara jenggot, bersiwak, istinsyaq (menghirup air ke dalam hidung,-pen), memotong kuku, membasuh persendian, mencabut bulu ketiak, mencukur bulu kemaluan, istinja’ (cebok) dengan air.” (HR. Muslim no. 627)
“Maka hadapkanlah wajahmu dengan lurus kepada agama Allah; (tetaplah atas) fitrah Allah yang telah menciptakan manusia menurut fitrah itu. Tidak ada penggantian pada fitrah Allah. (Itulah) agama yang lurus; tetapi kebanyakan manusia tidak mengetahui.” (QS. Ar Ruum [30] : 30)
Imam Nawawi rahimahullah mengatakan, “Kesimpulannya ada lima riwayat yang menggunakan lafazh
أَعْفُوا وَأَوْفُوا وَأَرْخُوا وَأَرْجُوا وَوَفِّرُوا”
Semua lafazh ini bermakna membiarkan jenggot tersebut sebagaimana adanya. (Al Minhaj Syarh Shahih Muslim, 3/151)

* SKB CAT
** Undang-Undang Keimigrasian
:PROPERTIES:
:CREATED:  [2024-12-12 Thu 23:58]
:END:

*** Bab 1 - Ketentuan Umum
:PROPERTIES:
:CREATED:  [2024-12-12 Thu 23:59]
:END:

**** Pasal 1
:PROPERTIES:
:CREATED:  [2024-12-12 Thu 23:59]
:END:

Dalam Undang-Undang ini yang dimaksud dengan:
- Keimigrasian adalah hal ihwal lalu lintas orang yang masuk atau keluar Wilayah Indonesia sertapengawasannya dalam rangka menjaga tegaknya kedaulatan negara.
- Wilayah Negara Republik Indonesia yang selanjutnya disebut Wilayah Indonesia adalah seluruh wilayah Indonesia serta zona tertentu yang ditetapkan berdasarkan undang-undang.
- Fungsi Keimigrasian adalah bagian dari urusan pemerintahan negara dalam memberikan pelayanan Keimigrasian, penegakan hukum, keamanan negara, dan fasilitator pembangunan kesejahteraan masyarakat.
- Menteri adalah menteri yang menyelenggarakan urusan pemerintahan di bidang hukum dan hak asasi manusia.
- Direktur Jenderal adalah Direktur Jenderal Imigrasi.
- Direktorat Jenderal Imigrasi adalah unsur pelaksana tugas dan fungsi Kementerian Hukum dan Hak Asasi Manusia di bidang Keimigrasian.
- Pejabat Imigrasi adalah pegawai yang telah melalui pendidikan khusus Keimigrasian dan memiliki keahlian teknis Keimigrasian serta memilik wewenang untuk melaksanakan tugas dan tanggung jawab berdasarkan Undang-Undang ini.
- Penyidik Pegawai Negeri Sipil Keimigrasian yang selanjutnya disebut dengan PPNS Keimigrasian adalah Pejabat Imigrasi yang diberi wewenang oleh undang-undang untuk melakukan penyidikan tindak pidana Keimigrasian.
- Orang Asing adalah orang yang bukan warga negara Indonesia.
- Sistem Informasi Manajemen Keimigrasian adalah sistem teknologi informasi dan komunikasi yang digunakan untuk mengumpulkan, mengolah dan menyajikan informasi guna mendukung operasional, manajemen, dan pengambilan keputusan dalam melaksanakan Fungsi Keimigrasian.
- Kantor Imigrasi adalah unit pelaksana teknis yang menjalankan Fungsi Keimigrasian di daerah kabupaten, kota, atau kecamatan.
- Tempat Pemeriksaan Imigrasi adalah tempat pemeriksaan di pelabuhan laut, bandar udara, pos lintas batas, atau tempat lain sebagai tempat masuk dan keluar Wilayah Indonesia.
- Dokumen Perjalanan adalah dokumen resmi yang dikeluarkan oleh pejabat yang berwenang dari suatu negara, Perserikatan Bangsa-Bangsa, atau organisasi internasional lainnya untuk melakukan perjalanan antarnegara yang memuat identitas pemegangnya.
- Dokumen Keimigrasian adalah Dokumen Perjalanan Republik Indonesia, dan Izin Tinggal yang dikeluarkan oleh Pejabat Imigrasi atau pejabat dinas luar negeri.
- Dokumen Perjalanan Republik Indonesia adalah Paspor Republik Indonesia dan Surat Perjalanan Laksana Paspor Republik Indonesia.
- Paspor Republik Indonesia yang selanjutnya disebut Paspor adalah dokumen yang dikeluarkan oleh Pemerintah Republik Indonesia kepada warga negara Indonesia untuk melakukan perjalanan antarnegara yang berlaku selama jangka waktu tertentu.
- Surat Perjalanan Laksana Paspor Republik Indonesia yang selanjutnya disebut Surat Perjalanan Laksana Paspor adalah dokumen pengganti paspor yang diberikan dalam keadaan tertentu yang berlaku selama jangka waktu tertentu.
- Visa Republik Indonesia yang selanjutnya disebut Visa adalah keterangan tertulis yang diberikan oleh pejabat yang berwenang di Perwakilan Republik Indonesia atau di tempat lain yang ditetapkan oleh Pemerintah Republik Indonesia yang memuat persetujuan bagi Orang Asing untuk melakukan perjalanan ke Wilayah Indonesia dan menjadi dasar untuk pemberian Izin Tinggal.
- Tanda Masuk adalah tanda tertentu berupa cap yang dibubuhkan pada Dokumen Perjalanan warga negara Indonesia dan Orang Asing, baik manual maupun elektronik, yang diberikan oleh Pejabat Imigrasi sebagai tanda bahwa yang bersangkutan masuk Wilayah Indonesia.
- Tanda Keluar adalah tanda tertentu berupa cap yang dibubuhkan pada Dokumen Perjalanan warga negara Indonesia dan Orang Asing, baik manual maupun elektronik, yang diberikan oleh Pejabat Imigrasi sebagai tanda bahwa yang bersangkutan keluar Wilayah Indonesia.
- Izin Tinggal adalah izin yang diberikan kepada Orang Asing oleh Pejabat Imigrasi atau pejabat dinas luar negeri untuk berada di Wilayah Indonesia.
- Pernyataan Integrasi adalah pernyataan Orang Asing kepada Pemerintah Republik Indonesia sebagai salah satu syarat memperoleh Izin Tinggal Tetap.
- Izin Tinggal Tetap adalah izin yang diberikan kepada Orang Asing tertentu untuk bertempat tinggal dan menetap di Wilayah Indonesia sebagai penduduk Indonesia.
- Izin Masuk Kembali adalah izin tertulis yang diberikan oleh Pejabat Imigrasi kepada Orang Asing pemegang Izin Tinggal terbatas dan Izin Tinggal Tetap untuk masuk kembali ke Wilayah Indonesia.
- Korporasi adalah kumpulan orang dan/atau kekayaan yang terorganisasi, baik merupakan badan hukum maupun bukan badan hukum.
- Penjamin adalah orang atau Korporasi yang bertanggung jawab atas keberadaan dan kegiatan Orang Asing selama berada di Wilayah Indonesia.
- Alat Angkut adalah kapal laut, pesawat udara, atau sarana transportasi lain yang lazim digunakan, baik untuk mengangkut orang maupun barang.
- Pencegahan adalah larangan sementara terhadap orang untuk keluar dari Wilayah Indonesia berdasarkan alasan Keimigrasian atau alasan lain yang ditentukan oleh undang-undang.
- Penangkalan adalah larangan terhadap Orang Asing untuk masuk Wilayah Indonesia berdasarkan alasan Keimigrasian.
- Intelijen Keimigrasian adalah kegiatan penyelidikan Keimigrasian dan pengamanan Keimigrasian dalam rangka proses penyajian informasi melalui analisis guna menetapkan perkiraan keadaan Keimigrasian yang dihadapi atau yang akan dihadapi.
- Tindakan Administratif Keimigrasian adalah sanksi administratif yang ditetapkan Pejabat Imigrasi terhadap Orang Asing di luar proses peradilan.
- Penyelundupan Manusia adalah perbuatan yang bertujuan mencari keuntungan, baik secara langsung maupun tidak langsung, untuk diri sendiri atau untuk orang lain yang membawa seseorang atau kelompok orang, baik secara terorganisasi maupun tidak terorganisasi, atau memerintahkan orang lain untuk membawa seseorang atau kelompok orang, baik secara terorganisasi maupun tidak terorganisasi, yang tidak memiliki hak secara sah untuk memasuki Wilayah Indonesia atau keluar Wilayah Indonesia dan/atau masuk wilayah negara lain yang orang tersebut tidak memiliki hak untuk memasuki wilayah tersebut secara sah, baik dengan menggunakan dokumen sah maupun dokumen palsu, atau tanpa menggunakan Dokumen Perjalanan, baik melalui pemeriksaan imigrasi maupun tidak.
- Rumah Detensi Imigrasi adalah unit pelaksana teknis yang menjalankan Fungsi Keimigrasian sebagai tempat penampungan sementara bagi Orang Asing yang dikenai Tindakan Administratif Keimigrasian.
- Ruang Detensi Imigrasi adalah tempat penampungan sementara bagi Orang Asing yang dikenai Tindakan Administratif Keimigrasian yang berada di Direktorat Jenderal Imigrasi dan Kantor Imigrasi.
- Deteni adalah Orang Asing penghuni Rumah Detensi Imigrasi atau Ruang Detensi Imigrasi yang telah mendapatkan keputusan pendetensian dari Pejabat Imigrasi.
- Deportasi adalah tindakan paksa mengeluarkan Orang Asing dari Wilayah Indonesia.
- Penanggung Jawab Alat Angkut adalah pemilik, pengurus, agen, nakhoda, kapten kapal, kapten pilot, atau pengemudi alat angkut yang bersangkutan.
- Penumpang adalah setiap orang yang berada di atas alat angkut, kecuali awak alat angkut.
- Perwakilan Republik Indonesia adalah Kedutaan Besar Republik Indonesia, Konsulat Jenderal Republik Indonesia, dan Konsulat Republik Indonesia

**** Pasal 2
:PROPERTIES:
:CREATED:  [2024-12-12 Thu 23:59]
:END:

Setiap warga negara Indonesia berhak melakukan perjalanan keluar dan masuk Wilayah Indonesia

*** Bab 2 - Pelaksanaan Fungsi Keimigrasian
:PROPERTIES:
:CREATED:  [2024-12-12 Thu 23:59]
:END:

**** Pasal 3
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

- Untuk melaksanakan Fungsi Keimigrasian, Pemerintah menetapkan kebijakan Keimigrasian
- Kebijakan Keimigrasian dilaksanakan oleh Menteri
- Fungsi Keimigrasian di sepanjang garis perbatasan Wilayah Indonesia dilaksanakan oleh Pejabat Imigrasi yang meliputi Tempat Pemeriksaan Imigrasi dan pos lintas bata

**** Pasal 4
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

- Untuk melaksanakan Fungsi Keimigrasian sebagaimana dimaksud dalam Pasal 3, dapat dibentuk Kantor Imigrasi di kabupaten, kota, atau kecamatan
- Di setiap wilayah kerja Kantor Imigrasi dapat dibentuk Tempat Pemeriksaan Imigrasi
- Pembentukan Tempat Pemeriksaan Imigrasi sebagaimana dimaksud pada ayat (2) ditetapkan berdasarkan Keputusan Menteri
- Selain Kantor Imigrasi sebagaimana dimaksud pada ayat (1), dapat  dibentuk Rumah Detensi Imigrasi di ibu kota negara, provinsi, kabupaten, atau kota
- Kantor Imigrasi dan Rumah Detensi Imigrasi merupakan unit pelaksana teknis yang berada di bawah Direktorat Jenderal Imigrasi

**** Pasal 5
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

Fungsi Keimigrasian di setiap Perwakilan Republik Indonesia atau tempat lain di luar negeri dilaksanakan oleh Pejabat Imigrasi dan/atau pejabat dinas luar negeri yang ditunjuk.

**** Pasal 6
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

Pemerintah dapat melakukan kerja sama internasional di bidang Keimigrasian dengan negara lain dan/atau dengan badan atau organisasi internasional berdasarkan ketentuan peraturan perundang-undangan.

**** Pasal 7
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

- Direktur Jenderal bertanggung jawab menyusun dan mengelola Sistem Informasi Manajemen Keimigrasian sebagai sarana pelaksanaan Fungsi Keimigrasian di dalam atau di luar Wilayah
- Sistem Informasi Manajemen Keimigrasian dapat diakses oleh instansi dan/atau lembaga pemerintahan terkait sesuai dengan tugas dan fungsinya

*** Bab 3 - Masuk dan Keluar Wilayah Indonesia
:PROPERTIES:
:CREATED:  [2024-12-12 Thu 23:59]
:END:

**** Pasal 8
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

- Setiap orang yang masuk atau keluar Wilayah Indonesia wajib memiliki Dokumen Perjalanan yang sah dan masih berlaku
- Setiap Orang Asing yang masuk Wilayah Indonesia wajib memiliki Visa yang sah dan masih berlaku, kecuali ditentukan lain berdasarkan Undang-Undang ini dan perjanjia

**** Pasal 9
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

- Setiap orang yang masuk atau keluar Wilayah Indonesia wajib melalui pemeriksaan yang dilakukan oleh Pejabat Imigrasi di Tempat Pemeriksaan
- Pemeriksaan sebagaimana dimaksud pada ayat (1) meliputi pemeriksaan Dokumen Perjalanan dan/atau identitas diri yang sah
- Dalam hal terdapat keraguan atas keabsahan Dokumen Perjalanan dan/atau identitas diri seseorang, Pejabat Imigrasi berwenang untuk melakukan penggeledahan terhadap badan dan barang bawaan dan dapat dilanjutkan dengan proses penyelidikan Keimigrasian

**** Pasal 10
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

Orang Asing yang telah memenuhi persyaratan dapat masuk Wilayah Indonesia setelah mendapatkan Tanda Masuk.

**** Pasal 11
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

- Dalam keadaan darurat Pejabat Imigrasi dapat memberikan Tanda Masuk yang bersifat darurat kepada Orang Asing
- Tanda Masuk sebagaimana dimaksud pada ayat (1) berlaku sebagai Izin Tinggal kunjungan dalam jangka waktu tertentu

**** Pasal 12
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

Menteri berwenang melarang Orang Asing berada di daerah tertentu di Wilayah Indonesia

**** Pasal 13
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

- Pejabat Imigrasi menolak Orang Asing masuk Wilayah Indonesia dalam hal orang asing tersebut:
    - namanya tercantum dalam daftar Penangkalan
    - tidak memiliki Dokumen Perjalanan yang sah dan berlaku
    - memiliki dokumen Keimigrasian yang palsu
    - tidak memiliki Visa, kecuali yang dibebaskan dari kewajiban memiliki Visa
    - telah memberi keterangan yang tidak benar dalam memperoleh Visa
    - menderita penyakit menular yang membahayakan kesehatan umum
    - terlibat kejahatan internasional dan tindak pidana transnasional yang terorganisasi
    - termasuk dalam daftar pencarian orang untuk ditangkap dari suatu negara asing
    - terlibat dalam kegiatan makar terhadap Pemerintah Republik Indonesia; ata
    - termasuk dalam jaringan praktik atau kegiatan prostitusi, perdagangan orang, dan penyelundupan manusia
- Orang Asing yang ditolak masuk sebagaimana dimaksud pada ayat (1) ditempatkan dalam pengawasan sementara menunggu proses pemulangan yang bersangkutan

**** Pasal 14
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

- Setiap warga negara Indonesia tidak dapat ditolak masuk Wilaya
- Dalam hal terdapat keraguan terhadap Dokumen Perjalanan seorang warga negara Indonesia dan/atau status kewarganegaraannya, yang bersangkutan harus memberikan bukti lain yang sah dan meyakinkan yang menunjukkan bahwa yang bersangkutan adalah warga negara Indonesia
- Dalam rangka melengkapi bukti sebagaimana dimaksud pada ayat (2), yang bersangkutan dapat ditempatkan dalam Rumah Detensi Imigrasi atau Ruang Detensi Imigrasi

**** Pasal 15
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

Setiap orang dapat keluar Wilayah Indonesia setelah memenuhi persyaratan dan mendapat Tanda Keluar dari Pejabat Imigrasi.

**** Pasal 16
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

- Pejabat Imigrasi menolak orang untuk keluar Wilayah Indonesia dalam hal orang tersebut:
    - tidak memiliki Dokumen Perjalanan yang sah dan masih berlaku;
    - diperlukan untuk kepentingan penyelidikan dan penyidikan atas permintaan pejabat yang berwenang; atau
    - namanya tercantum dalam daftar Pencegahan.
- Pejabat Imigrasi juga berwenang menolak Orang  Asing untuk keluar Wilayah Indonesia dalam hal Orang Asing tersebut masih mempunyai kewajiban di Indonesia yang harus diselesaikan sesuai dengan ketentuan peraturan perundang-undangan

**** Pasal 17
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

- Penanggung Jawab Alat Angkut yang masuk atau keluar Wilayah Indonesia dengan alat angkutnya wajib melalui Tempat Pemeriksaan Imigrasi.
- Penanggung Jawab Alat Angkut yang membawa penumpang yang akan masuk atau keluar Wilayah Indonesia hanya dapat menurunkan atau menaikkan penumpang di Tempat Pemeriksaan Imigrasi.
- Nakhoda kapal laut wajib melarang Orang Asing yang tidak memenuhi persyaratan untuk meninggalkan alat angkutnya selama alat angkut tersebut berada di Wilayah Indonesia

**** Pasal 18
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

- Penanggung Jawab Alat Angkut yang datang dari luar Wilayah Indonesia atau akan berangkat keluar Wilayah Indonesia diwajibkan untuk:
    - sebelum kedatangan atau keberangkatan memberitahukan rencana kedatangan atau rencana keberangkatan secara tertulis atau elektronik kepada Pejabat Imigrasi;
    - menyampaikan daftar penumpang dan daftar awak alat angkut yang ditandatanganinya kepada Pejabat Imigrasi;
    - memberikan tanda atau mengibarkan bendera isyarat bagi kapal laut yang datang dari luar Wilayah Indonesia dengan membawa penumpang;
    - melarang setiap orang naik atau turun dari alat angkut tanpa izin Pejabat Imigrasi sebelum dan selama dilakukan pemeriksaan Keimigrasian;
    - melarang setiap orang naik atau turun dari alat angkut yang telah mendapat penyelesaian Keimigrasian selama menunggu keberangkatan;
    - membawa kembali keluar Wilayah Indonesia pada kesempatan pertama setiap Orang Asing yang tidak memenuhi persyaratan yang datang dengan alat angkutnya;
    - menjamin bahwa Orang Asing yang diduga atau dicurigai akan masuk ke Wilayah Indonesia secara tidak sah untuk tidak turun dari alat angkutnya; dan
    - menanggung segala biaya yang timbul sebagai akibat pemulangan setiap penumpang dan/atau awak alat angkutnya.
- Penanggung Jawab Alat Angkut reguler wajib menggunakan sistem informasi pemrosesan pendahuluan data penumpang dan melakukan kerja sama dalam rangka pemberitahuan data penumpang melalui Sistem Informasi Manajemen Keimigrasian-

**** Pasal 19
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

- Penanggung Jawab Alat Angkut wajib memeriksa Dokumen Perjalanan dan/atau Visa setiap penumpang yang akan melakukan perjalanan masuk Wilayah Indonesia.
- Pemeriksaan sebagaimana dimaksud pada ayat (1) dilakukan sebelum penumpang naik ke alat angkutnya yang akan menuju Wilayah
- Penanggung Jawab Alat Angkut sebagaimana dimaksud pada ayat (1) wajib menolak untuk mengangkut setiap penumpang yang tidak memiliki Dokumen Perjalanan, Visa, dan/atau Dokumen Keimigrasian yang sah dan masih berlaku.
- Jika dalam pemeriksaan Keimigrasian oleh Pejabat Imigrasi ditemukan ada penumpang sebagaimana dimaksud pada ayat (3), Penanggung Jawab Alat Angkut dikenai sanksi berupa biaya beban dan wajib membawa kembali penumpang tersebut keluar Wilayah Indonesia

**** Pasal 20
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

Pejabat Imigrasi yang bertugas berwenang naik ke alat angkut yang berlabuh di pelabuhan, mendarat di bandar udara, atau berada di post lintas batas untuk kepentingan pemeriksaan Keimigrasian.

**** Pasal 21
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

Dalam hal terdapat dugaan adanya pelanggaran terhadap ketentuan sebagaimana dimaksud dalam Pasal 17 atau Pasal 18, Pejabat Imigrasi berwenang memerintahkan Penanggung Jawab Alat Angkut untuk menghentikan atau membawa alat angkutnya ke suatu tempat guna kepentingan pemeriksaan Keimigrasian

**** Pasal 22
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

- Setiap Tempat Pemeriksaan Imigrasi ditetapkan suatu area tertentu untuk melakukan pemeriksaan Keimigrasian yang disebut dengan area tertentu untuk melakukan pemeriksaan Keimigrasian yang disebut dengan area imigrasi.
- Area imigrasi merupakan area terbatas yang hanya dapat dilalui oleh penumpang atau awak alat angkut yang akan keluar atau masuk Wilayah Indonesia atau pejabat dan petugas yang berwenang.
- Kepala Kantor Imigrasi bersama-sama dengan penyelenggara bandar udara, pelabuhan laut, dan pos lintas batas menetapkan area imigrasi sebagaimana dimaksud pada ayat (1).
- Penyelenggara bandar udara, pelabuhan laut, dan pos lintas batas dapat mengeluarkan tanda untuk memasuki area imigrasi setelah mendapat persetujuan kepala Kantor Imigrasi.

**** Pasal 23
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

Ketentuan lebih lanjut mengenai persyaratan dan tata cara masuk dan keluar Wilayah Indonesia diatur dengan Peraturan Pemerintah.

*** Bab 4 - Dokumen Perjalanan Republik Indonesia
:PROPERTIES:
:CREATED:  [2024-12-12 Thu 23:59]
:END:

**** Pasal 24
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

- Dokumen Perjalanan Republik Indonesia terdiri atas
    - Paspor; dan
    - Surat Perjalanan Laksana
- Paspor terdiri atas
    - Paspor diplomatik
    - Paspor dinas; dan
    - Paspor biasa
- Surat Perjalanan Laksana Paspor terdiri atas:
    - Surat Perjalanan Laksana Paspor untuk warga negara Indonesia;
    - Surat Perjalanan Laksana Paspor untuk Orang Asing; dan
    - surat perjalanan lintas batas atau pas lintas batas
- Dokumen Perjalanan Republik Indonesia sebagaimana dimaksud pada ayat (1) merupakan dokumen negara

**** Pasal 25
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

- Paspor diplomatik diterbitkan bagi warga negara Indonesia yang akan melakukan perjalanan keluar Wilayah Indonesia dalam rangka penempatan atau perjalanan tugas yang bersifat diplomatik
- Paspor dinas diterbitkan bagi warga negara Indonesia yang akan melakukan perjalanan keluar Wilayah Indonesia dalam rangka penempatan atau perjalanan dinas yang tidak bersifat diplomati
- Paspor diplomatik dan Paspor dinas sebagaimana dimaksud pada ayat (1) dan ayat (2) diterbitkan oleh Menteri Luar Negeri

**** Pasal 26
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

- Paspor biasa diterbitkan untuk warga negara Indonesia
- Paspor biasa sebagaimana dimaksud pada ayat (1) diterbitkan oleh Menteri atau Pejabat Imigrasi yang ditunjuk

**** Pasal 27
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

- Surat Perjalanan Laksana Paspor untuk warga negara Indonesia dikeluarkan bagi warga negara Indonesia dalam keadaan tertentu jika Paspor biasa tidak dapat diberikan.
- Surat Perjalanan Laksana Paspor untuk Orang Asing dikeluarkan bagi Orang Asing yang tidak mempunyai Dokumen Perjalanan yang sah dan negaranya tidak mempunyai perwakilan di Indonesia.
- Surat Perjalanan Laksana Paspor sebagaimana dimaksud pada ayat (2) diberikan dalam hal:
    - atas kehendak sendiri keluar Wilayah Indonesia sepanjang tidak terkena pencegahan;
    - dikenai Deportasi; atau
    - repatriasi.
- Surat Perjalanan Laksana Paspor diterbitkan oleh Menteri atau Pejabat Imigrasi yang ditunjuk

**** Pasal 28
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

Surat Perjalanan Laksana Paspor dapat dikeluarkan untuk orang perseorangan atau kolektif.

**** Pasal 29
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

- Surat perjalanan lintas batas atau pas lintas batas dapat dikeluarkan bagi warga negara Indonesia yang berdomisili di wilayah perbatasan negara Republik Indonesia dengan negara lain sesuai dengan perjanjian lintas batas.
- Surat perjalanan lintas batas atau pas lintas batas diterbitkan oleh Menteri atau Pejabat Imigrasi yang ditunjuk

**** Pasal 30
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

Setiap warga negara Indonesia hanya diperbolehkan memegang 1 (satu) Dokumen Perjalanan Republik Indonesia yang sejenis atas namanya sendiri yang masih berlaku.

**** Pasal 31
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

- Menteri atau Pejabat Imigrasi yang ditunjuk berwenang melakukan penarikan atau pencabutan Paspor biasa, Surat Perjalanan Laksana Paspor, dan surat perjalanan lintas batas atau pas lintas batas yang telah dikeluarkan.
- Menteri Luar Negeri atau pejabat yang ditunjuk berwenang melakukan penarikan atau pencabutan Paspor diplomatik dan Paspor dinas.
- Penarikan Paspor biasa dilakukan dalam hal:
    - pemegangnya melakukan tindak pidana atau melanggar peraturan perundang-undangan di Indonesia; atau
    - pemegangnya termasuk dalam daftar Pencegahan

**** Pasal 32
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

- Menteri atau Pejabat Imigrasi yang ditunjuk bertanggung jawab atas perencanaan, pengadaan, penyimpanan, pendistribusian, dan pengamanan blanko dan formulir:
    - Paspor biasa;
    - Surat Perjalanan Laksana Paspor; dan
    - surat perjalanan lintas batas atau pas lintas batas.
- Menteri atau Pejabat Imigrasi yang ditunjuk menetapkan spesifikasi teknis pengamanan dengan standar bentuk, ukuran, desain, fitur pengamanan, dan isi blanko sesuai dengan standar internasional serta formulir:
    - Paspor biasa;
    - Surat Perjalanan Laksana Paspor; dan
    - surat perjalanan lintas batas atau pas lintas batas.
- Pejabat Imigrasi atau pejabat yang ditunjuk berwenang melakukan pengisian dan pencatatan, baik secara manual maupun elektronik, dalam blanko dan formulir:
    - Paspor biasa;
    - Surat Perjalanan Laksana Paspor; dan
    - surat perjalanan lintas batas atau pas lintas batas

**** Pasal 33
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

Ketentuan lebih lanjut mengenai tata cara dan persyaratan pemberian, penarikan, pembatalan, pencabutan, penggantian, serta pengadaan blanko dan standardisasi Dokumen Perjalanan Republik Indonesia diatur dengan Peraturan Pemerintah

*** Bab 5 - Visa tanda masuk dan Izin Tinggal
:PROPERTIES:
:CREATED:  [2024-12-12 Thu 23:59]
:END:

**** Pasal 34
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

Visa terdiri atas:
    - Visa diplomatik
    - Visa dinas
    - Visa kunjungan; dan
    - Visa tinggal terbatas

**** Pasal 35
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

Visa diplomatik diberikan kepada Orang Asing pemegang Paspor diplimatik dan paspor lain untuk mmasuk Wilayah Indonesia guna melaksanakan tugas yang bersifat diplomatik.

**** Pasal 36
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

Visa dinas diberikan kepada Orang Asing pemegang Paspor dinas dan Paspor lain yang akan melakukan perjalanan ke Wilayah Indonesia dalam rangka melaksanakan tugas resmi yang tidak bersifat diplomatik dari pemerintah asing yang bersangkutan atau organisasi internasional.

**** Pasal 37
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

Pemberian Visa diplomatik dan Visa dinas merupakan kewenangan Menteri Luar Negeri dan dalam pelaksanaannya dikeluarkan oleh pejabat dinas luar negeri di Perwakilan Republik Indonesia.

**** Pasal 38
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

Visa kunjungan diberikan kepada Orang Asing yang akan melakukan perjalanan ke Wilayah Indonesia dalam rangka kunjungan tugas pemerintahan, pendidikan, sosial budaya, pariwisata, bisnis, keluarga, jurnalistik, atau singgah untuk meneruskan perjalanan ke negara lain.

**** Pasal 39
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

Visa tinggal terbatas diberikan kepada Orang Asing:
- sebagai rohaniawan, tenaga ahli, pekerja, peneliti, pelajar, investor, lanjut usia, dan keluarganya, serta Orang Asing yang kawin secara sah dengan warga negara Indonesia, yang akan melakukan perjalanan ke Wilayah Indonesia untuk bertempat tinggal dalam jangka waktu yang terbatas; atau
- dalam rangka bergabung untuk bekerja di atas kapal, alat apung, atau instalasi yang beroperasi di wilayah perairan nusantara, laut teritorial, landas kontinen, dan/atau Zona Ekonomi Eksklusif Indonesia.

**** Pasal 40
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:
1. Pemberian Visa kunjungan dan Visa tinggal terbatas merupakan kewenangan Menteri.
2. Visa sebagaimana dimaksud pada ayat (1) diberikan dan ditandatangani oleh Pejabat Imigrasi di Perwakilan Republik Indonesia di luar negeri.
3. Dalam hal Perwakilan Republik Indonesia belum ada Pejabat Imigrasi sebagaimana dimaksud pada ayat (2), pemberian Visa kunjungan dan Visa tinggal terbatas dilaksanakan oleh pejabat dinas luar negeri.
4. Pejabat dinas luar negeri sebagaimana dimaksud pada ayat (3) berwenang memberikan Visa setelah memperoleh Keputusan Menteri.

**** Pasal 41
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:
1. Visa kunjungan dapat juga diberikan kepada Orang Asing pada saat kedatangan di Tempat Pemeriksaan Imigrasi.
2. Orang Asing yang dapat diberikan Visa kunjungan saat kedatangan adalah warga negara dari negara tertentu yang diterapkan berdasarkan Peraturan Menteri.
3. Pemberian Visa kunjungan saat kedatangan di Tempat Pemeriksaan Imigrasi sebagaimana dimaksud pada ayat (1) dilaksanakan oleh Pejabat Imigrasi.

**** Pasal 42
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:
Permohonan Visa ditolak dalam hal pemohon:
1. namanya tercantum dalam daftar Penangkalan;
2. tidak memiliki Dokumen Perjalanan yang sah dan masih berlaku;
3. tidak cukup memiliki biaya hidup bagi dirinya dan/atau keluarganya selama berada di Indonesia;
4. tidak memiliki tiket kembali atau tiket terusan untuk melanjutkan perjalanan ke negara lain;
5. tidak memiliki Izin Masuk Kembali ke negara asal atau tidak memiliki visa ke negara lain;
6. menderita penyakit menular, gangguan jiwa, atau hal lain yang dapat membahayakan kesehatan atau ketertiban umum;
7. terlibat tindak pidana transnasional yang terorganisasi atau membahayakan keutuhan wilayah Negara Kesatuan Republik Indonesia; dan/atau
8. termasuk dalam jaringan praktik atau kegiatan prostitusi, perdagangan orang, dan penyelundupan manusia.

**** Pasal 43
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:
1. Dalam hal tertentu Orang Asing dapat dibebaskan dari kewajiban memiliki Visa.
2. Orang Asing yang dibebaskan dari kewajiban memiliki Visa sebagaimana dimaksud pada ayat (1) adalah:
    a. warga negara dari negara tertentu yang ditetapkan berdasarkan Peraturan Presiden dengan memperhatikan asas timbal balik dan asas manfaat;
    b. warga negara asing pemegang Izin Tinggal yang memiliki Izin Masuk Kembali yang masih berlaku;
    c. nakhoda, kapten pilot, atau awak yang sedang bertugas di alat angkut;
    d. nakhoda, awak kapal, atau tenaga ahli asing di atas kapal laut atau alat apung yang datang langsung dengan alat angkutnya untuk beroperasi di perairan Nusantara, laut teritorial, landas kontinen, dan/atau Zona Ekonomi Eksklusif Indonesia.

**** Pasal 44
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:
1. Orang Asing dapat masuk Wilayah Indonesia setelah mendapat Tanda Masuk.
2. Tanda Masuk diberikan oleh Pejabat Imigrasi di Tempat Pemeriksaan Imigrasi kepada Orang Asing yang telah memenuhi persyaratan masuk Wilayah Indonesia.

**** Pasal 45
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

*** Bab 6
:PROPERTIES:
:CREATED:  [2024-12-12 Thu 23:59]
:END:

**** Pasal 3
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

**** Pasal 4
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

**** Pasal 5
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

**** Pasal 6
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

**** Pasal 7
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

*** Bab 7
:PROPERTIES:
:CREATED:  [2024-12-12 Thu 23:59]
:END:

**** Pasal 3
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

**** Pasal 4
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

**** Pasal 5
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

**** Pasal 6
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

**** Pasal 7
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

*** Bab 8
:PROPERTIES:
:CREATED:  [2024-12-12 Thu 23:59]
:END:

**** Pasal 3
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

**** Pasal 4
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

**** Pasal 5
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

**** Pasal 6
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

**** Pasal 7
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

*** Bab 9
:PROPERTIES:
:CREATED:  [2024-12-12 Thu 23:59]
:END:

**** Pasal 3
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

**** Pasal 4
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

**** Pasal 5
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

**** Pasal 6
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

**** Pasal 7
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

*** Bab 10
:PROPERTIES:
:CREATED:  [2024-12-12 Thu 23:59]
:END:

**** Pasal 3
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

**** Pasal 4
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

**** Pasal 5
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

**** Pasal 6
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

**** Pasal 7
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

*** Bab 11
:PROPERTIES:
:CREATED:  [2024-12-12 Thu 23:59]
:END:

**** Pasal 3
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

**** Pasal 4
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

**** Pasal 5
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

**** Pasal 6
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

**** Pasal 7
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

*** Bab 12
:PROPERTIES:
:CREATED:  [2024-12-12 Thu 23:59]
:END:

**** Pasal 3
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

**** Pasal 4
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

**** Pasal 5
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

**** Pasal 6
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

**** Pasal 7
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

*** Bab 13
:PROPERTIES:
:CREATED:  [2024-12-12 Thu 23:59]
:END:

**** Pasal 3
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

**** Pasal 4
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

**** Pasal 5
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

**** Pasal 6
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

**** Pasal 7
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

*** Bab 14
:PROPERTIES:
:CREATED:  [2024-12-12 Thu 23:59]
:END:

**** Pasal 3
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

**** Pasal 4
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

**** Pasal 5
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

**** Pasal 6
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

**** Pasal 7
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

*** Bab 15
:PROPERTIES:
:CREATED:  [2024-12-12 Thu 23:59]
:END:

**** Pasal 3
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

**** Pasal 4
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

**** Pasal 5
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

**** Pasal 6
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

**** Pasal 7
:PROPERTIES:
:CREATED:  [2024-12-13 Fri 00:00]
:END:

