* SKB Wawancara
** Kelebihan dan Kekurangan

   Kelebihan : saya bekerja keras, jujur, suka belajar hal yang baru, bisa berbahasa inggris, mampu mengoperasikan banyak alat perkantoran, pandai menggunakan komputer
   Kekurangan : saya harus fokus saat bekerja

** Latar belakang pendidikan, pengalaman berorganisasi, dan pengalaman bekerja

   untuk mengetahui kompetensi sosial yang anda miliki: 

*** sekolah di SMAN 1 Banda Aceh
*** di rohis SMA, anggota pengurus ekskul bulutangkis SMA
*** bekerja di Fotokopi
*** mengikuti Course/pelatihan di bidang pemrograman web
** Profil Kemenkumham RI

   https://www.kemenkumham.go.id/profil/tentang-kementerian-hukum-ri/sejarah-kementerian-hukum-ri

*** Sejarah

Kementerian Hukum dan Hak Asasi Manusia Republik Indonesia (disingkat Kemenkumham RI) adalah kementerian dalam Pemerintah Indonesia yang membidangi urusan hukum dan hak asasi manusia. Kementerian Hukum dan Hak Asasi Manusia berada di bawah dan bertanggung jawab kepada Presiden. Kementerian Hukum dan Hak Asasi Manusia dipimpin oleh seorang Menteri yang sejak 27 Oktober 2014 dijabat oleh Yasonna Laoly. Kemenkumham beberapa kali mengalami pergantian nama yakni: "Departemen Kehakiman" (1945-1999), "Departemen Hukum dan Perundang-undangan" (1999-2001), "Departemen Kehakiman dan Hak Asasi Manusia" (2001-2004), "Departemen Hukum dan Hak Asasi Manusia" (2004-2009), dan "Kementerian Hukum dan Hak Asasi Manusia" (2009-sekarang).
Kementerian Hukum dan Hak Asasi Manusia pertama kali dibentuk pada tanggal 19 Agustus 1945 dengan nama Departemen Kehakiman. Menteri Kehakiman yang pertama menjabat adalah Soepomo. Kementerian Hukum dan Hak Asasi Manusia pada zaman pemerintahan Belanda disebut Departemen Van Justitie yaitu berdasarkan peraturan Herdeland Yudie Staatblad No.576.
Dalam sidang PPKI tahun 1945 menetapkan mengenai Departemen Kehakiman dalam struktur Negara menurut UUD. Dalam UUD tadi disebutkan departemen termasuk Departemen Kehakiman yang mengurus tentang pengadilan, penjara, kejaksaan dan sebagainya. Dalam sidang PPKI tersebut dibuat pula penetapan tentang tugas pokok masalah ruang lingkup tugas Departemen Kehakiman walaupun secara singkat masih mengacu kepada peraturan Herdeland Yudie Staatblad No.576.
Pada tanggal 1 Oktober 1945 kewenangan Departemen Kehakiman diperluas yakni Kejaksaan berdasarkan Maklumat Pemerintah tahun 1945 tanggal 1 0ktober 1945 dan Jawatan Topograpi berdasarkan Penetapan pemerintah tahun 1945 Nomor 1/S.D. Jawatan Topograpi kemudian dikeluarkan dari Departemen Kehakiman dan masuk ke Departemen Pertahanan berdasarkan Penetapan Pemerintah tahun 1946 nomor 8/S.D.
Ketika Departemen Agama dibentuk pada tanggal 3 Januari 1946, Mahkamah Islam Tinggi dikeluarkan dari Departemen Kehakiman Republik Indonesia dan masuk ke Departemen Agama Republik Indonesia berdasarkan penetapan pemerintah tahun 1946 Nomor 5/S.D.
Pada 22 Juli 1960, rapat kabinet memutuskan bahwa kejaksaan menjadi departemen dan keputusan tersebut dituangkan dalam Keputusan Presiden RI Nomor 204/1960 tertanggal 1 Agustus 1960 yang berlaku sejak 22 Juli 1960. Sejak itu pula, Kejaksaan RI dipisahkan dari Departemen Kehakiman. Pemisahan tersebut dilatarbelakangi rencana kejaksaan mengusut kasus yang melibatkan Menteri Kehakiman pada saat itu.
Pengalihan Peradilan Umum dan Peradilan Tata Usaha Negara dari Kementerian Hukum dan Hak Asasi Manusia ke Mahkamah Agung berawal dari Undang-Undang No 35 Tahun 1999 tentang Ketentuan-ketentuan Pokok Kekuasaan Kehakiman yang kemudian dijabarkan dalam Undang-Undang No. 4 Tahun 2004 tentang Kekuasaan Kehakiman dan Undang-Undang No. 5 Tahun 2004 tentang Perubahan atas Undang-Undang No. 14 Tahun 1985 tentang Mahkamah Agung. Pada tanggal 23 Maret 2004 Presiden Megawati mengeluarkan Keputusan Presiden RI No. 21 Tahun 2004 tentang pengalihan organisasi, administrasi dan finansial dan lingkungan Peradilan Umum dan Tata Usaha Negara, Pengadilan Agama ke Mahkamah Agung yang kemudian ditindaklanjuti dengan serah terima Pengalihan organisasi, administrasi dan finansial di lingkungan Peradilan Umum dan Peradilan Tata Usaha Negara ke Mahkamah Agung pada tanggal 31 Maret 2004.
Nama Departemen Kehakiman telah beberapa kali berubah nama karena disesuaikan dengan fungsi dari Departemen tersebut yaitu dari Departemen Kehakiman menjadi Departemen Hukum dan Perundang Undangan dan sekarang menjadi Kementerian Hukum Dan Hak Asasi Manusia.
Kantor wilayah (kanwil) Kementerian Hukum dan Hak Asasi Manusia merupakan instansi vertikal Kementerian Hukum dan Hak Asasi Manusia yang berkedudukan di setiap provinsi, yang berada di bawah dan bertanggung jawab kepada Menteri Hukum dan Hak Asasi Manusia. Kanwil terdiri atas beberapa divisi serta sejumlah Unit Pelaksana Teknis (UPT), termasuk Kantor Imigrasi, Lembaga Pemasyarakatan (Lapas), Lapas Terbuka • Lapas Narkotika, Rumah Tahanan Negara (Rutan), Cabang Rutan, Rumah Penyimpanan Benda Sitaan Negara (Rupbasan), Balai Pemasyarakatan (Bapas), Balai Harta Peninggalan (BHP), serta Rumah Detensi Imigrasi (Rudenim).

*** Visi, Misi dan Tata Nilai

Visi :"Kementerian Hukum dan Hak Asasi Manusia yang Andal, Profesional, Inovatif, dan Berintegritas dalam pelayanan kepada Presiden dan Wakil Presiden untuk mewujudkan Visi dan Misi Presiden dan Wakil Presiden Indonesia Maju yang Berdaulat, Mandiri, dan Berkepribadian berlandaskan Gotong Royong".
Misi :
    Membentuk peraturan Perundang-Undangan yang berkualitas dan melindungi kepentingan nasional;
    Menyelenggarakan pelayanan publik di bidang hukum yang berkualitas;
    Mendukung penegakan Hukum di Bidang Kekayaan Intelektual, Keimigrasian, Administrasi Hukum Umum, dan Pemasyarakatan yang bebas dari korupsi, bermartabat dan terpercaya;
    Melaksanakan penghormatan, perlindungan dan pemenuhan Hak Asasi Manusia yang berkelanjutan;
    Melaksanakan peningkatan Kesadaran Hukum Masyarakat;
    Ikut serta menjaga stabilitas keamanan melalui peran Keimigrasian dan Pemasyarakatan; serta
    Melaksanakan tata laksana pemerintahan yang baik melalui Reformasi Birokrasi dan Kelembagaan.
Tata Nilai:
 1. Profesional  	: 	Aparatur Kementerian Hukum dan HAM adalah aparat yang bekerja keras untuk mencapai tujuan organisasi melalui penguasaan bidang tugasnya, menjunjung tinggi etika dan integirtas profesi;
 2. Akuntabel 	: 	Setiap kegiatan dalam rangka penyelenggaraan pemerintah dapat dipertanggungjawabkan kepada masyarakat sesuai dengan ketentuan atau peraturan yang berlaku;
 3. 	Sinergi 	: 	Komitmen untuk membangun dan memastikan hubungan kerjasama yang produktif serta kemitraan yang harmonis dengan para pemangku kepentingan untuk menemukan dan melaksanakan solusi terbaik, bermanfaat, dan berkualitas;
 4. 	Transparan 	: 	Kementerian Hukum dan HAM menjamin akses atau kebebasan bagi setiap orang untuk memperoleh informasi tentang penyelenggaraan pemerintahan, yakni informasi tentang kebijakan, proses pembuatan dan pelaksanaannya, serta hasil-hasil yang dicapai;
 5. 	Inovatif 	: 	Kementerian Hukum dan HAM mendukung kreatifitas dan mengembangkan inisiatif untuk selalu melakukan pembaharuan dalam penyelenggaraan tugas dan fungsinya.

*** Tugas dan Fungsi

Tugas :
"Kementerian Hukum dan Hak Asasi Manusia mempunyai tugas menyelenggarakan urusan pemerintahan di bidang hukum dan hak asasi manusia untuk membantu Presiden dalam menyelenggarakan pemerintahan negara."
Fungsi:
Dalam melaksanakan tugas sebagaimana dimaksud dalam Pasal 4 Peraturan Menteri Hukum dan HAM Nomor 28 Tahun 2023, Kementerian Hukum dan Hak Asasi Manusia menyelenggarakan fungsi:

    perumusan, penetapan dan pelaksanaan kebijakan di bidang peraturan perundang-undangan, administrasi hukum umum, pemasyarakatan, keimigrasian, kekayaan intelektual, dan hak asasi manusia;
    koordinasi pelaksanaan tugas, pembinaan, dan pemberian dukungan administrasi kepada seluruh unsur organisasi di lingkungan Kementerian Hukum dan Hak Asasi Manusia;
    pengelolaan barang milik/kekayaan negara yang menjadi tanggung jawab Kementerian Hukum dan Hak Asasi Manusia;
    pengawasan atas pelaksanaan tugas di lingkungan Kementerian Hukum dan Hak Asasi Manusia;
    pelaksanaan bimbingan teknis dan supervisi atas pelaksanaan urusan Kementerian Hukum dan Hak Asasi Manusia di daerah;
    pelaksanaan pembinaan hukum nasional;
    perumusan, penyusunan, dan pemberian rekomendasi strategi kebijakan di bidang hukum dan hak asasi manusia;
    pelaksanaan pengembangan sumber daya manusia di bidang hukum dan hak asasi manusia;
    pelaksanaan kegiatan teknis yang berskala nasional;
    pelaksanaan tugas pokok sampai ke daerah; 
    pelaksanaan dukungan yang bersifat substantif kepada seluruh unsur organisasi di lingkungan Kementerian Hukum dan Hak Asasi Manusia; dan
    pelaksanaan fungsi lain yang diberikan oleh Presiden.

*** Struktur Organisasi
** Kode etik profesi

   Sasanti imigrasi: "Bhumi Pura Wira Wibawa" artinya pengawal pintu gerbang yang dalam pelaksanaan tugas berdasarkan asas kemanusiaan, keadilan sehingga menumbuhkan integritas wibawa kepada masyarakat luas
   Tri fungsi imigrasi :
1. Pengaturan tentang berbagai hal mengenai lalu lintas orang keluar, masuk dan tinggal dari dan ke dalam wilayah negara Republik Indonesia;
2. Pengaturan tentang berbagai hal mengenai pengawasan orang asing di wilayah Repubik Indonesia;
3. Pemeriksaan dokumen perjalanan, baik negara yang ditinggalkan, negara yang dikunjungi, maupun negara yang dilalui.
   Panca Bhakti Insan Imigrasi :
1. Takwa
2. Menjunjung tinggi kehormatan
3. Cendekia
4. Integritas Pribadi
5. Inovatif

** Alasan mendaftar CPNS

   berikan jawaban yang memiliki kesan positif: ingin ikut berkontribusi memajukan bangsa dan negara

** Alasan mengapa memilih Ditjen imigrasi
** Tugas dan Fungsi Ditjen Imigrasi

Bagian Kesatu
Kedudukan, Tugas dan Fungsi

Pasal 547

    Direktorat Jenderal Imigrasi berada di bawah dan bertanggung jawab kepada Menteri.
    Direktorat Jenderal Imigrasi dipimpin oleh Direktur Jenderal.

Pasal 548
Direktorat Jenderal Imigrasi mempunyai tugas menyelenggarakan perumusan dan pelaksanaan kebijakan di bidang keimigrasian sesuai dengan ketentuan peraturan perundang-undangan.

Pasal 549
Dalam melaksanakan tugas sebagaimana dimaksud dalam Pasal 548, Direktorat Jenderal Imigrasi menyelenggarakan fungsi:

    perumusan kebijakan di bidang penegakan hukum dan keamanan keimigrasian, pelayanan dan fasilitas keimigrasian, perlintasan negara dan kerja sama luar negeri keimigrasian, dan Teknologi informasi keimigrasian;
    pelaksanaan kebijakan di bidang penegakan hukum dan keamanan keimigrasian, pelayanan dan fasilitas keimigrasian, perlintasan negara dan kerja sama luar negeri keimigrasian, dan teknologi informasi keimigrasian;
    pemberian bimbingan teknis dan supervisi di bidang penegakan hukum dan keamanan keimigrasian, pelayanan dan fasilitas keimigrasian, perlintasan negara dan kerja sama luar negeri keimigrasian, dan teknologi informasi keimigrasian;
    pelaksanaan pemantauan, evaluasi, dan pelaporan di bidang penegakan hukum dan keamanan keimigrasian, pelayanan dan fasilitas keimigrasian, perlintasan negara dan kerja sama luar negeri keimigrasian, dan teknologi informasi keimigrasian;
    pelaksanaan administrasi Direktorat Jenderal Imigrasi; dan
    pelaksanaan fungsi lain yang diberikan oleh Menteri.

** Hukum Menjaga Jenggot

“Potong pendeklah kumis dan biarkanlah (peliharalah) jenggot.” (HR. Muslim no. 623)
“Selisilah orang-orang musyrik. Potong pendeklah kumis dan biarkanlah jenggot.” (HR. Muslim no. 625)
“Pendekkanlah kumis dan biarkanlah (perihalah) jenggot dan selisilah Majusi.” (HR. Muslim no. 626)
“Ada sepuluh macam fitroh, yaitu memendekkan kumis, memelihara jenggot, bersiwak, istinsyaq (menghirup air ke dalam hidung,-pen), memotong kuku, membasuh persendian, mencabut bulu ketiak, mencukur bulu kemaluan, istinja’ (cebok) dengan air.” (HR. Muslim no. 627)
“Maka hadapkanlah wajahmu dengan lurus kepada agama Allah; (tetaplah atas) fitrah Allah yang telah menciptakan manusia menurut fitrah itu. Tidak ada penggantian pada fitrah Allah. (Itulah) agama yang lurus; tetapi kebanyakan manusia tidak mengetahui.” (QS. Ar Ruum [30] : 30)
Imam Nawawi rahimahullah mengatakan, “Kesimpulannya ada lima riwayat yang menggunakan lafazh
أَعْفُوا وَأَوْفُوا وَأَرْخُوا وَأَرْجُوا وَوَفِّرُوا”
Semua lafazh ini bermakna membiarkan jenggot tersebut sebagaimana adanya. (Al Minhaj Syarh Shahih Muslim, 3/151)

* SKB CAT
