#+title: Quick Capture
#+author: Muhammad Reza Ananta
:PROPERTIES:
:year:     2024
:END:

* Al-Quran Surah Al-Fatihah (1-7)

1. 

* Ta'lim 20240814
:PROPERTIES:
:CREATED:  [2024-08-14 Wed 21:18]
:END:

- viral kdrt: mengajak nikah lebih cepat itu baik tapi harus berilmu
- nabi sering meminta maaf kepada istrinya sampai mereka merasa malu sendiri
- QS. Yusuf
- cerita tentang bani israil: yang boleh diceritakan, tidak boleh dan tidak bertentangan
- cara anak-anak nabi ya'kub as berbohong
- nabi ya'kub as bersabar dan tidak langsung melaknat 
- nabi yusuf as dijual oleh saudaranya
- dibeli oleh perdana menteri mesir
- perbedaan perdana menteri dan raja
- kenapa Allah swt melarang anak angkat
- zulaikha menggoda nabi yusuf as
- nabi yusuf as meminta perlindungan kepada Allah swt dan tidak mau berkhianat kepada ayah angkatnya
- zulaikha mengfitnah nabi yusuf as dan memenjarakannya
- zulaikha digunjing oleh perempuan2 setempat
- zulaikha mengundang perempuan2 tersebut untuk melihat nabi yusuf as 
- perempuan2 tersebut tidak sengaja memotong jari mereka dan berkata bahwa nabi yusuf as adalah seorang malaikat yang agung

* Adab sebelum tidur
:PROPERTIES:
:CREATED:  [2024-12-09 Mon 00:21]
:END:

** Tidur di awal malam
:PROPERTIES:
:CREATED:  [2024-12-09 Mon 00:22]
:END:

Pertama, tidur di awal malam. Landasan ini didasarkan pada hadis fi’liyyah Nabi Muhammad Saw tentang kurang baiknya berbincang-bincang sesuatu yang kurang bermanfaat setelah waktu isya. Dari Abu Barzah: “Bahwasanya Rasulullah Saw tidak menyukai tidur sebelum salat Isya’ dan berbincang-bincang setelahnya.” (HR. Bukhari dan Muslim).

** Berwudhu
:PROPERTIES:
:CREATED:  [2024-12-09 Mon 00:22]
:END:

Kedua, mengambil air wudhu. Hal ini berdasarkan hadis al-Baro’ bin ‘Azib, Nabi shallallahu ‘alaihi wa sallam bersabda: “Jika kamu mendatangi tempat tidurmu maka wudhulah seperti wudhu untuk salat”.  (HR. Bukhari no. 247).

** Berbaring pada sisi kanan
:PROPERTIES:
:CREATED:  [2024-12-09 Mon 00:23]
:END:

Ketiga, berbaring pada sisi kanan badan. Sama dengan hadis sebelumnya, hal ini berdasarkan hadis Al Baro’ bin ‘Azib, Nabi Saw: “Jika kamu mendatangi tempat tidurmu maka wudhulah seperti wudhu untuk salat, lalu berbaringlah pada sisi kanan badanmu” (HR. Bukhari no. 247 dan Muslim no. 2710). Rasulullah Saw cenderung kurang menyukai tidur dengan posisi tengkurap.

** Meniup telapak tangan dan membaca surah 3 qul
:PROPERTIES:
:CREATED:  [2024-12-09 Mon 00:25]
:END:

Keempat, meniup kedua telapak tangan lalu mengucap QS. Al-Ikhlas, QS. Al-Falaq, dan QS. An-Naas, masing-masing sekali. Setelah itu usapkan kedua tangan tersebut ke wajah dan bagian tubuh yang dapat dijangkau. Hal ini dilakukan sebanyak tiga kali. Amalan ini dicontohkan oleh Nabi Sawsebagaimana hadis riwayat dari ‘Aisyah, beliau berkata:

Nabi Saw ketika berada di tempat tidur di setiap malam, beliau mengumpulkan kedua telapak tangannya lalu kedua telapak tangan tersebut ditiup dan dibacakan ’Qul huwallahu ahad’ (surat Al Ikhlash), ’Qul a’udzu birobbil falaq’ (surat Al Falaq) dan ’Qul a’udzu birobbin naas’ (surat An Naas). Kemudian beliau mengusapkan kedua telapak tangan tadi pada anggota tubuh yang mampu dijangkau dimulai dari kepala, wajah, dan tubuh bagian depan. Beliau melakukan yang demikian sebanyak tiga kali.” (HR. Bukhari no. 5017).

** Membaca ayatul kursi
:PROPERTIES:
:CREATED:  [2024-12-09 Mon 00:26]
:END:

Kelima, membaca Ayat Kursi. Landasan ini terjadi ketika Abu Hurairah ditugasi menjaga harta zakat Ramadan kemudian ada seseorang yang mencuri harta tersebut. Namun kemudian Abu Harairah merebut kembali harta tersebut. Masalah ini kemudian diadukan kepada Rasulullah saw oleh Abu Hurairah. Lalu Abu Hurairah menceritakan suatu hadis berkenaan dengan ini: “Jika kamu hendak berbaring di atas tempat tidurmu, bacalah ayat Al Kursi karena dengannya kamu selalu dijaga oleh Allah Ta’ala.” (HR. Bukhari no. 3275).

** Membaca doa tidur
:PROPERTIES:
:CREATED:  [2024-12-09 Mon 00:26]
:END:

Keenam, membaca doa tidur. Setelah hal-hal yang di atas dijalankan, maka pada tahap akhir sebelum akhirnya kita terlelap adalah dengan membaca doa. Landasan doa ini berasal dari hadis yang diriwayatkan oleh Hudzaifah, berikut doanya:

بِاسْمِكَ اللَّهُمَّ أَحْيَا وَأموتُ

* How to communicate clearly
:PROPERTIES:
:CREATED:  [2024-08-27 Tue 22:09]
:END:

First and foremost you need to be able to think clearly 

** Know your goal
:PROPERTIES:
:CREATED:  [2024-08-27 Tue 22:10]
:END:

whatever you're doing/say, keep your goal in mind. Whether you want the other person to be aligned with you or you want to pushback on what the other person wants 

** Know your audience
:PROPERTIES:
:CREATED:  [2024-08-27 Tue 22:10]
:END:

** Know how you're going to say it
:PROPERTIES:
:CREATED:  [2024-08-27 Tue 22:11]
:END:

